title:            A journey always starts with a single step
mytitle:          Andrea Rafanelli
url:              //andrearafanelli.github.io


############################
## LANGUAGE
############################

defaultContentLanguage: en
hasCJKLanguage: false
defaultContentLanguageInSubdir: false
removePathAccents: true


owner:
  name:           Andrea Rafanelli
  avatar:         photo.jpg.png
  linkedin: andrea-rafanelli
  github: andrearafanelli
links:
  #- title: Publications
  #  url: /publications/
  - title: Curriculum
    url: /cv/
  - title: Contact
    url: /contact/

timezone:    Europe/Rome
future:      true
pygments:    true
highlighter: rouge
markdown:    kramdown
kramdown:
  extensions: ["strikethrough"]

permalink:   /:categories/:title/

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  coderay:
    coderay_line_numbers:
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: class

include: [".htaccess"]
exclude: ["lib", "config.rb", "Capfile", "config", "log", "Rakefile", "Rakefile.rb", "tmp", "less", "*.sublime-project", "*.sublime-workspace", "test", "spec", "Gruntfile.js", "package.json", "node_modules", "Gemfile", "Gemfile.lock", "LICENSE", "README.md"]
